import { IndustryPreset, FinancingOption, Scenario } from './types';

export const industryPresets: IndustryPreset[] = [
  {
    id: 'retail',
    name: 'Розничная торговля',
    description: 'Магазины, торговые центры, розничные сети',
    icon: '🛍️',
    characteristics: {
      seasonality: 0.7,
      volatility: 0.6,
      dso: 15,
      dpo: 30,
      dio: 45,
    },
    financingOptions: [
      {
        id: 'retail-credit',
        name: 'Торговый кредит',
        type: 'credit',
        description: 'Кредит на пополнение товарных запасов',
        minAmount: 500000,
        maxAmount: 5000000,
        interestRate: 12,
        term: 12,
        requirements: ['Опыт работы от 1 года', 'Оборот от 2 млн руб/мес'],
        advantages: ['Быстрое одобрение', 'Гибкие условия', 'Сезонные льготы'],
        disadvantages: ['Высокая ставка', 'Требует залога'],
        suitability: 95,
        industrySpecific: true,
      },
      {
        id: 'retail-factoring',
        name: 'Факторинг дебиторки',
        type: 'factoring',
        description: 'Финансирование под уступку дебиторской задолженности',
        minAmount: 100000,
        maxAmount: 10000000,
        interestRate: 8,
        term: 6,
        requirements: ['Дебиторка от надежных покупателей', 'Оборот от 1 млн руб/мес'],
        advantages: ['Низкая ставка', 'Быстрое получение средств', 'Без залога'],
        disadvantages: ['Ограниченный круг покупателей', 'Комиссии'],
        suitability: 90,
        industrySpecific: true,
      },
    ],
    typicalScenarios: [
      {
        id: 'retail-seasonal',
        name: 'Сезонный рост продаж',
        type: 'optimistic',
        description: 'Увеличение продаж в предпраздничный период',
        parameters: {
          revenueChange: 0.3,
          costChange: 0.1,
          paymentDelay: 0,
          seasonalityFactor: 1.5,
        },
        results: {
          cashFlow: [100000, 150000, 200000, 180000],
          riskScore: 20,
          recommendations: ['Увеличить товарные запасы', 'Настроить логистику', 'Подготовить персонал'],
        },
        timeframe: 'short',
      },
    ],
  },
  {
    id: 'services',
    name: 'Услуги',
    description: 'Консалтинг, IT, маркетинг, юридические услуги',
    icon: '💼',
    characteristics: {
      seasonality: 0.3,
      volatility: 0.4,
      dso: 30,
      dpo: 15,
      dio: 0,
    },
    financingOptions: [
      {
        id: 'services-overdraft',
        name: 'Овердрафт',
        type: 'overdraft',
        description: 'Краткосрочное финансирование для покрытия кассовых разрывов',
        minAmount: 100000,
        maxAmount: 2000000,
        interestRate: 15,
        term: 1,
        requirements: ['Стабильный оборот', 'Хорошая кредитная история'],
        advantages: ['Гибкость использования', 'Быстрое получение'],
        disadvantages: ['Высокая ставка', 'Ограниченная сумма'],
        suitability: 85,
        industrySpecific: false,
      },
    ],
    typicalScenarios: [
      {
        id: 'services-delay',
        name: 'Задержка платежей клиентов',
        type: 'stress',
        description: 'Клиенты задерживают оплату на 30-60 дней',
        parameters: {
          revenueChange: -0.2,
          costChange: 0,
          paymentDelay: 45,
          seasonalityFactor: 1,
        },
        results: {
          cashFlow: [50000, 30000, 20000, 10000],
          riskScore: 80,
          recommendations: ['Ужесточить условия оплаты', 'Ввести предоплату', 'Использовать факторинг'],
        },
        timeframe: 'short',
      },
    ],
  },
  {
    id: 'ecommerce',
    name: 'Электронная коммерция',
    description: 'Интернет-магазины, маркетплейсы, цифровые товары',
    icon: '🛒',
    characteristics: {
      seasonality: 0.8,
      volatility: 0.7,
      dso: 5,
      dpo: 45,
      dio: 30,
    },
    financingOptions: [
      {
        id: 'ecommerce-investment',
        name: 'Инвестиционный кредит',
        type: 'investment',
        description: 'Финансирование развития платформы и маркетинга',
        minAmount: 1000000,
        maxAmount: 10000000,
        interestRate: 10,
        term: 24,
        requirements: ['Растущий оборот', 'План развития', 'Команда'],
        advantages: ['Долгосрочное финансирование', 'Низкая ставка'],
        disadvantages: ['Сложное одобрение', 'Требует бизнес-план'],
        suitability: 80,
        industrySpecific: true,
      },
    ],
    typicalScenarios: [
      {
        id: 'ecommerce-growth',
        name: 'Быстрый рост',
        type: 'optimistic',
        description: 'Увеличение трафика и продаж в 3 раза',
        parameters: {
          revenueChange: 2.0,
          costChange: 0.5,
          paymentDelay: 0,
          seasonalityFactor: 1.2,
        },
        results: {
          cashFlow: [200000, 400000, 600000, 800000],
          riskScore: 30,
          recommendations: ['Масштабировать инфраструктуру', 'Нанять персонал', 'Увеличить маркетинг'],
        },
        timeframe: 'medium',
      },
    ],
  },
  {
    id: 'construction',
    name: 'Строительство',
    description: 'Жилищное и коммерческое строительство, ремонт',
    icon: '🏗️',
    characteristics: {
      seasonality: 0.5,
      volatility: 0.8,
      dso: 60,
      dpo: 90,
      dio: 120,
    },
    financingOptions: [
      {
        id: 'construction-project',
        name: 'Проектное финансирование',
        type: 'credit',
        description: 'Финансирование конкретного строительного проекта',
        minAmount: 5000000,
        maxAmount: 100000000,
        interestRate: 14,
        term: 36,
        requirements: ['Лицензия на строительство', 'Залог недвижимости', 'Договоры с заказчиками'],
        advantages: ['Большие суммы', 'Долгосрочное финансирование'],
        disadvantages: ['Высокие требования', 'Сложное одобрение'],
        suitability: 90,
        industrySpecific: true,
      },
    ],
    typicalScenarios: [
      {
        id: 'construction-delay',
        name: 'Задержка сдачи объекта',
        type: 'stress',
        description: 'Задержка сдачи объекта на 6 месяцев',
        parameters: {
          revenueChange: -0.4,
          costChange: 0.2,
          paymentDelay: 180,
          seasonalityFactor: 1,
        },
        results: {
          cashFlow: [-500000, -300000, -200000, -100000],
          riskScore: 90,
          recommendations: ['Пересмотреть договоры', 'Искать дополнительное финансирование', 'Оптимизировать расходы'],
        },
        timeframe: 'long',
      },
    ],
  },
  {
    id: 'manufacturing',
    name: 'Производство',
    description: 'Промышленное производство, переработка, сборка',
    icon: '🏭',
    characteristics: {
      seasonality: 0.4,
      volatility: 0.5,
      dso: 45,
      dpo: 60,
      dio: 90,
    },
    financingOptions: [
      {
        id: 'manufacturing-equipment',
        name: 'Лизинг оборудования',
        type: 'leasing',
        description: 'Финансирование приобретения производственного оборудования',
        minAmount: 1000000,
        maxAmount: 50000000,
        interestRate: 8,
        term: 60,
        requirements: ['Техническое обоснование', 'Гарантии поставщика'],
        advantages: ['Низкая ставка', 'Налоговые льготы', 'Быстрое одобрение'],
        disadvantages: ['Ограниченный выбор оборудования'],
        suitability: 95,
        industrySpecific: true,
      },
    ],
    typicalScenarios: [
      {
        id: 'manufacturing-seasonal',
        name: 'Сезонное снижение спроса',
        type: 'pessimistic',
        description: 'Снижение заказов в летний период',
        parameters: {
          revenueChange: -0.3,
          costChange: 0.1,
          paymentDelay: 30,
          seasonalityFactor: 0.7,
        },
        results: {
          cashFlow: [80000, 60000, 40000, 20000],
          riskScore: 60,
          recommendations: ['Диверсифицировать продукцию', 'Искать новые рынки', 'Оптимизировать производство'],
        },
        timeframe: 'medium',
      },
    ],
  },
  {
    id: 'logistics',
    name: 'Логистика',
    description: 'Транспортные услуги, складирование, доставка',
    icon: '🚚',
    characteristics: {
      seasonality: 0.6,
      volatility: 0.7,
      dso: 20,
      dpo: 30,
      dio: 15,
    },
    financingOptions: [
      {
        id: 'logistics-fleet',
        name: 'Финансирование автопарка',
        type: 'leasing',
        description: 'Лизинг транспортных средств',
        minAmount: 2000000,
        maxAmount: 20000000,
        interestRate: 9,
        term: 48,
        requirements: ['Лицензия на перевозки', 'Стабильный оборот'],
        advantages: ['Низкая ставка', 'Налоговые льготы'],
        disadvantages: ['Долгосрочные обязательства'],
        suitability: 90,
        industrySpecific: true,
      },
    ],
    typicalScenarios: [
      {
        id: 'logistics-fuel',
        name: 'Рост цен на топливо',
        type: 'stress',
        description: 'Увеличение стоимости топлива на 50%',
        parameters: {
          revenueChange: 0,
          costChange: 0.3,
          paymentDelay: 0,
          seasonalityFactor: 1,
        },
        results: {
          cashFlow: [120000, 100000, 80000, 60000],
          riskScore: 70,
          recommendations: ['Пересмотреть тарифы', 'Оптимизировать маршруты', 'Рассмотреть альтернативы'],
        },
        timeframe: 'short',
      },
    ],
  },
];
